language: java

env:
  global:
  - secure: aDH/ZX8DkSq5cN0kgFz2XSiSxYFFM7jA4qAVIgVj7Yuf+wYvfkbRyNwqHJPhCe2OWMXDrFjPso8aFxQAQOQ4Y+3GVT2InAfKIumphn89sYf+zDXY2WqwBF7lgK+ByjwbmPIkEu4Y/vSe7ONN+EcurBeiokUGDaofj6xh7kvsrwQ=

after_success:
  - ./gradlew docs
  - ".utility/initiate-publish.sh"

deploy:
  provider: releases
  api_key:
    secure: Y4hsQ9lTvzjuAyukZwJMJmcl9Y+PlR5GNOI0HsNIA8jrMpsuLXZu5JU+onHLaiMWBtTyUn155bVD0gy59ashEqI2j5mo9Q+0scQtd7H7PFsecXz0L+ZB/0b+Pc3tPxq4CvHekdXbdeyekpzDV7r9NiddtjNOGQBWVbA5HFBaNXs=
  file:
    - jplot2d-core/build/libs/jplot2d-core-1.0.0.jar
    - jplot2d-core/target/jplot2d-core-1.0.0-ext-libs.zip
    - jplot2d-swing/target/jplot2d-swing-1.0.0-full.jar
    - jplot2d-swt/target/jplot2d-swt-1.0.0-full.jar
  skip_cleanup: true
  on:
    repo: jplot2d/jplot2d
    tags: true
    all_branches: true
